### PR TITLE
fix(levm): handle slicing and indexing errors

### LINKED ISSUE #1074: LEVM: add `#[forbid(clippy::unwrap_used)]`, `#[forbid(clippy::expect_used)]`, and `#[forbid(clippy::panic)]`
1. Add the lints `#[forbid(clippy::unwrap_used)]`, `#[forbid(clippy::expect_used)]`, and `#[forbid(clippy::panic)]` to the `levm` module.
2. Handle the errors or propagate them as needed.

### PR DESCRIPTION
**Pull request by JereSalo**
**Motivation**

**Description**

Partially Closes #1074

### CODE REVIEW

File: crates/vm/levm/src/opcode_handlers/environment.rs [hunk 1]
```diff
@@ -115,7 +115,14 @@ impl VM {
...
 
-            padded_calldata[..data_len_to_copy].copy_from_slice(&calldata[..data_len_to_copy]);
+            padded_calldata
+                .get_mut(..data_len_to_copy)
+                .ok_or(VMError::SlicingError)?
+                .copy_from_slice(
+                    calldata
+                        .get(..data_len_to_copy)
+                        .ok_or(VMError::SlicingError)?,
+                );
```
Comment (ilitteri) [inline crates/vm/levm/src/opcode_handlers/environment.rs:125]: Avoid this error handling by refactoring the logic. We can create the resulting data this way:
```rust
// All bytes after the end of the calldata are set to 0.
let mut data = [0u8; 32];
for (i, byte) in current_call_frame.calldata.iter().skip(offset).take(32).enumerate() {
    if let Some(data_byte) = data.get_mut(i) {
        *data_byte = *byte;
    }
}
let result = U256::from_big_endian(&data);
```

Comment (ilitteri) [reply crates/vm/levm/src/opcode_handlers/environment.rs:125]: The best error handling is the one that doesn't need to be handled because of refactoring 😛. If the refactor is too complex, then we handle the error.

File: crates/vm/levm/src/vm.rs [hunk 2]
```diff
@@ -430,7 +449,7 @@ impl VM {
                 return Err(VMError::ContractOutputTooBig);
             }
             // Supposing contract code has contents
-            if contract_code[0] == INVALID_CONTRACT_PREFIX {
+            if *contract_code.first().ok_or(VMError::IndexingError)? == INVALID_CONTRACT_PREFIX {
```
Comment (ilitteri) [inline crates/vm/levm/src/vm.rs:452]: `VMError::Internal(InternalError::TriedToIndexEmptyCode)`.

File: crates/vm/levm/src/vm.rs [hunk 3]
```diff
@@ -597,12 +622,17 @@ impl VM {
...
+        sender_address: Address,
+        sender_nonce: u64,
+    ) -> Result<Address, VMError> {
         let mut encoded = Vec::new();
         (sender_address, sender_nonce).encode(&mut encoded);
         let mut hasher = Keccak256::new();
         hasher.update(encoded);
-        Address::from_slice(&hasher.finalize()[12..])
+        Ok(Address::from_slice(
+            hasher.finalize().get(12..).ok_or(VMError::SlicingError)?,
```
Comment (ilitteri) [inline crates/vm/levm/src/vm.rs:634]: `VMError::Internal(InternalError::CouldNotComputeCreateAddress)`.

File: crates/vm/levm/src/vm.rs [hunk 4]
```diff
@@ -625,7 +655,9 @@ impl VM {
         hasher.update(sender_address.as_bytes());
         hasher.update(salt_bytes);
         hasher.update(initialization_code_hash);
-        Address::from_slice(&hasher.finalize()[12..])
+        Ok(Address::from_slice(
+            hasher.finalize().get(12..).ok_or(VMError::SlicingError)?,
```
Comment (ilitteri) [inline crates/vm/levm/src/vm.rs:659]: `VMError::Internal(InternalError::CouldNotComputeCreate2Address)`.

File: crates/vm/levm/src/opcode_handlers/environment.rs [hunk 5]
```diff
@@ -185,7 +192,14 @@ impl VM {
             let mut padded_calldata = vec![0u8; size];
             let data_len_to_copy = calldata.len().min(size);
 
-            padded_calldata[..data_len_to_copy].copy_from_slice(&calldata[..data_len_to_copy]);
+            padded_calldata
```
Comment (ilitteri) [inline crates/vm/levm/src/opcode_handlers/environment.rs:195]: We could probably refactor this to avoid handling this.

**Review by ilitteri — CHANGES_REQUESTED** [review]
The PR is looking good. Most of the errors here belong to an "internal" context. I suggest implementing the following error-handling hierarchy 

```rust
#[derive(Debug, thiserror::Error)]
pub enum VMError {
    ...
    #[error("Internal error: {0}")]
    Internal(#[from] InternalError),
}

#[derive(Debug, thiserror::Error)]
pub enum InternalError {
    #[error("Tried to access first call frame but found none")]
    CouldNotAccessFirstCallframe,
    #[error("Tried to read from empty code")]
    TriedToIndexEmptyCode,
    #[error("Failed computing CREATE address")]
    CouldNotComputeCreateAddress,
    #[error("Failed computing CREATE2 address")]
    CouldNotComputeCreate2Address,
    #[error("Tried to slice non-existing data")]
    SlicingError,
}
```

> [!NOTE]
> The best error handling is the one we do not need to handle. We can usually avoid handling errors by refactoring code.

File: crates/vm/levm/src/memory.rs [hunk 6]
```diff
@@ -71,14 +71,27 @@ impl Memory {
...
+                .ok_or(VMError::SlicingError)?,
+        );
 
-        self.data[dest_offset..dest_offset + size].copy_from_slice(&temp);
+        self.data
+            .get_mut(dest_offset..dest_offset + size)
+            .ok_or(VMError::SlicingError)?
+            .copy_from_slice(&temp);
+        Ok(())
     }
```
[the remark this answers is not in the document]
Comment (JereSalo) [reply crates/vm/levm/src/memory.rs]: Done!

File: crates/vm/levm/src/opcode_handlers/environment.rs (hunk 1 above)
Comment (JereSalo) [reply crates/vm/levm/src/opcode_handlers/environment.rs]: Done!

File: crates/vm/levm/src/vm.rs (hunk 2 above)
Comment (JereSalo) [reply crates/vm/levm/src/vm.rs]: Done!

File: crates/vm/levm/src/vm.rs (hunk 3 above)
Comment (JereSalo) [reply crates/vm/levm/src/vm.rs]: Done!

File: crates/vm/levm/src/opcode_handlers/environment.rs (hunk 5 above)
Comment (JereSalo) [reply crates/vm/levm/src/opcode_handlers/environment.rs]: Done!

File: crates/vm/levm/src/opcode_handlers/environment.rs (hunk 1 above)
Comment (JereSalo) [reply crates/vm/levm/src/opcode_handlers/environment.rs]: https://github.com/lambdaclass/lambda_ethereum_rust/pull/1107/commits/39db5919f8559a6003552453100360def426ce7c

File: crates/vm/levm/src/opcode_handlers/environment.rs (hunk 5 above)
Comment (JereSalo) [reply crates/vm/levm/src/opcode_handlers/environment.rs]: https://github.com/lambdaclass/lambda_ethereum_rust/pull/1107/commits/e9b8381909a60a40c7ed64a95189e0cd8665b563

File: crates/vm/levm/src/vm.rs (hunk 4 above)
Comment (JereSalo) [reply crates/vm/levm/src/vm.rs]: https://github.com/lambdaclass/lambda_ethereum_rust/pull/1107/commits/b25bc2afc515aa62e365accccec05772457aa8b0

File: crates/vm/levm/src/vm.rs (hunk 3 above)
Comment (JereSalo) [reply crates/vm/levm/src/vm.rs]: https://github.com/lambdaclass/lambda_ethereum_rust/pull/1107/commits/b25bc2afc515aa62e365accccec05772457aa8b0

File: crates/vm/levm/src/vm.rs (hunk 2 above)
Comment (JereSalo) [reply crates/vm/levm/src/vm.rs]: https://github.com/lambdaclass/lambda_ethereum_rust/pull/1107/commits/b25bc2afc515aa62e365accccec05772457aa8b0

**Review by ilitteri — APPROVED** [review]
LGTM
