### PR TITLE
fix(l1): made the tx-spammer work with our node

### LINKED ISSUE #1026: Make the tx_spammer additional service start working with our client
After solving #847 we were able to be the first node in the `network_params.yaml` file, and so, being the target of the [transaction spammer](https://github.com/MariusVanDerWijden/tx-fuzz). The node was working as part of the kurtosis devnet and assertoor test went through but the tx spammer immediately stops with:

```
No seed provided, creating one
Internal Error: Could not resolve block number
sending at f93ee4cf8c6c40b329b0c0626f28333c132cf241
error getting pending nonce; could not airdrop: Internal Error: Could not resolve block number
```

The objective of this issue is having the tx spammer running, not solving every issue that appears on the runs, if we are able to get an initial transaction going through, then we can start creating new issues for specific errors encountered by the fuzzer.

### PR DESCRIPTION
**Pull request by rodrigo-o**
**Motivation**

Have the tx spammer running instead of immediatly shutting down when we are the first node in the devnet setup.

**Description**

This PR tackled a couple of issues until we were able to process an initial transaction, (they are small changes):
- We were returning an error on `eth_getTransactionCount` when we either didn't have a `latest` block before genesis or at any point when we don't have `pending` blocks. The solution in this case was returning `0x0` in those cases.
- When requesting `eth_getTransactionCount` on `pending` after some transaction went through we were defaulting to `0x0`, it appears that the idea is to default to the `latest` in those case which make sense.
- There were a missing filter that made the node panic when building payloads for transactions with fees lower than the base_fee_per_gas, this generated that those kind of transactions stopped the node's ability to build blocks when they were in the mempool, we made a quick workaround in this PR, but will remove it in favor of #1018 

Closes #1026

### CODE REVIEW

File: crates/blockchain/mempool.rs [hunk 1]
```diff
@@ -79,6 +79,13 @@ pub fn filter_transactions(
         if filter.only_plain_txs && is_blob_tx || filter.only_blob_txs && !is_blob_tx {
             return false;
         }
+
+        // This is a temporary fix to avoid invalid transactions to be included.
+        // This should be removed once https://github.com/lambdaclass/ethereum_rust/issues/680
+        // is addressed.
+        if tx.effective_gas_tip(filter.base_fee).is_none() {
+            return false;
+        }
```
Comment (rodrigo-o) [inline crates/blockchain/mempool.rs:88]: This will be removed in favor of #1018

**Comment by rodrigo-o** [comment]
This is an example of a tx going through, the caveat here is that this tx was sent at the beggining and we needed to get to the 90th block to have a `base_fee` lower than our `gas_fee_cap`:

image

`gas_price` was set to 5000 on those transactions and it required the network to ran for a particular amount of time before getting the `base_fee` below that number (we didn't had `gas_fee_cap` set). 

```rust
    pub fn gas_fee_cap(&self) -> u64 {
        self.max_fee_per_gas().unwrap_or(self.gas_price())
    }
    
    pub fn effective_gas_tip(&self, base_fee: Option<u64>) -> Option<u64> {
        let Some(base_fee) = base_fee else {
            return Some(self.gas_tip_cap());
        };
        self.gas_fee_cap()
            .checked_sub(base_fee)
            .map(|tip| min(tip, self.gas_tip_cap()))
    }
```

We'll need to look into it deeper, given that I was able to run the same transactions in geth; but on our side, bypassing the check we still get an error from the VM that the `gas_price` is lower than the `base_fee_per_gas`. Here is an example of them being immediatly picked up, I started the spammer in the 13th slot.

image

**Comment by rodrigo-o** [comment]
**Some other errors spotted but not resolved**

_nonce 0 too low_:

Error on tx_spammer: `Vm execution error: Invalid Transaction: nonce 0 too low, expected 240`

But hitting the `eth_getTransactionCount` with `"params": ["0xf93ee4cf8c6c40b329b0c0626f28333c132cf241", "pending" | "latest"],` the answer is correct 
``` json
{
	"id": 1,
	"jsonrpc": "2.0",
	"result": "0xf0"
}
```

_EOF_:

Error on tx_spammer: `Post "http://127.0.0.1:50506": EOF`

Logs shows an issue with an overflow outside of u64

```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/primitive-types-0.12.2/src/lib.rs:38:1:
Integer overflow when casting to u64
```

This happens [here](https://github.com/lambdaclass/lambda_ethereum_rust/blob/66f1d1b15900070fd70a69bf2eca88ab13beeaa4/crates/networking/rpc/eth/transaction.rs#L464) in some particular transactions:
```rust
        if self.transaction.gas_price != 0 {
            highest_gas_limit = recap_with_account_balances(
                highest_gas_limit,
                &self.transaction,
                &storage,
                block_header.number,
            )?;
        }
```

File: test_data/network_params.yaml [hunk 2]
```diff
@@ -20,4 +20,6 @@ assertoor_params:
   run_block_proposal_check: false
   run_blob_transaction_test: true
   tests:
-    - 'https://raw.githubusercontent.com/lambdaclass/lambda_ethereum_rust/refs/heads/main/test_data/el-stability-check.yml'
\ No newline at end of file
+    - 'https://raw.githubusercontent.com/lambdaclass/lambda_ethereum_rust/refs/heads/main/test_data/el-stability-check.yml'
+tx_spammer_params:
+  tx_spammer_extra_args: ["--accounts=10", --txcount=10]
```
Comment (mpaulucci) [inline test_data/network_params.yaml:25]: these parameters are based on our current capabilities?

Comment (rodrigo-o) [reply test_data/network_params.yaml:25]: Not really, this is mostly to be able to track the execution instead of having hundreds of transactions (Which by the way we still need to check why we just add one as [shown in the image](https://github.com/lambdaclass/lambda_ethereum_rust/pull/1027#issuecomment-2448479005)). Most of the initial issues regarding the node being unable to propose weren't related to concurrency as I initially thought but to the errors mentioned in the PR description.

File: crates/blockchain/mempool.rs (hunk 1 above)
Comment (rodrigo-o) [reply crates/blockchain/mempool.rs]: Done!

**Review by mpaulucci — APPROVED** [review]
